USE master
CREATE DATABASE QLNS
USE QLNS
GO
CREATE TABLE NHANVIEN(
MANV INT IDENTITY(1,1) PRIMARY KEY,
TENNV NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
GIOTINH BIT NOT NULL,
DIACHI VARCHAR(100) NOT NULL,
DIENTHOAI INT NULL,
EMAIL VARCHAR(50) NOT NULL,
LOAINV INT NOT NULL,
MACV INT NOT NULL,
MACM INT NOT NULL,
MALUONG INT NOT NULL,
MAPB INT NOT NULL,
MATDHV INT NOT NULL,
MADCL INT NOT NULL,
)
GO
CREATE TABLE LUONG(
MALUONG INT IDENTITY(1,1) PRIMARY KEY,
MANV INT NOT NULL,
HESOLUONG INT NOT NULL,
LUONGCB INT NOT NULL,
LUONGTHUONG NOT NULL,
KHOANTRU NOT NULL,
)
GO
CREATE TABLE CHUCVU(
MACV INT IDENTITY(1,1) PRIMARY KEY,
TENCHUCVU NVARCHAR(30) NOT NULL,
PHUCAP INT NOT NULL,
GHICU NVARCHAR(200) NULL,
)
GO
CREATE TABLE PHONGBAN(
MAPB INT IDENTITY(1,1) PRIMARY KEY,
TENPB NVARCHAR(200) NOT NULL,
DIENTHOAI INT NOT NULL,
)
GO
CREATE TABLE CHUYENMON(
MACM INT IDENTITY(1,1) PRIMARY KEY,
TENCM NVARCHAR(100) NOT NULL,
)