USE master
CREATE DATABASE QLNS
USE QLNS
GO
CREATE TABLE NHANVIEN(
MANV INT IDENTITY(1,1) PRIMARY KEY,
TENNV NVARCHAR(100) NOT NULL,
NGAYSINH DATE NOT NULL,
CMND INT NOT NULL,
GIOTINH BIT NOT NULL,
DIACHI VARCHAR(100) NOT NULL,
DIENTHOAI INT NULL,
EMAIL VARCHAR(50) NOT NULL,
LOAINV INT NOT NULL,
MACV INT NOT NULL,
MACM INT NOT NULL,
MALUONG INT NOT NULL,
MAPB INT NOT NULL,
MATDHV INT NOT NULL,
MADCL INT NOT NULL
)
GO
CREATE TABLE LUONG(
MALUONG INT IDENTITY(1,1) PRIMARY KEY,
MANV INT NOT NULL,
HESOLUONG FLOAT NOT NULL,
LUONGCB FLOAT NOT NULL,
LUONGTHUONG FLOAT NOT NULL,
KHOANTRU FLOAT NOT NULL
)
GO
CREATE TABLE CHUCVU(
MACV INT IDENTITY(1,1) PRIMARY KEY,
TENCHUCVU NVARCHAR(30) NOT NULL,
PHUCAP FLOAT NOT NULL,
GHICU NVARCHAR(200) NULL
)
GO
CREATE TABLE PHONGBAN(
MAPB INT IDENTITY(1,1) PRIMARY KEY,
TENPB NVARCHAR(200) NOT NULL,
DIENTHOAI INT NOT NULL
)
GO 
CREATE TABLE TRINHDOHV
(
MATDHV INT IDENTITY(1,1) PRIMARY KEY,
TENHV NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE CHAMCONG
(
MACC INT IDENTITY(1,1) PRIMARY KEY,
MANV INT NOT NULL,
SOBUOI INT NULL

)
--TAO KHOAN NGOAI--
ALTER TABLE NHANVIEN ADD CONSTRAINT lUONG_NHANVIEN FOREIGN KEY (MALUONG) REFERENCES LUONG(MALUONG)
ALTER TABLE NHANVIEN ADD CONSTRAINT CHUCVU_NHANVIEN FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV)
ALTER TABLE NHANVIEN ADD CONSTRAINT PHONGBAN_NHANVIEN FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
ALTER TABLE NHANVIEN ADD CONSTRAINT TRINHDO_NHANVIEN FOREIGN KEY (MATDHV) REFERENCES TRINHDOHV(MATDHV)
ALTER TABLE CHAMCONG ADD CONSTRAINT CHAMCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)